project: "COUNTDOWN"
name: "COUNTDOWN_RFT_Qwen_1.5B_GRPO_Baseline"
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: grpo
  kl_loss_fn: k3
  kl_loss_fn_args:
    kl_coef: 0.01
  repeat_times: 8
  optimizer:
    lr: 1e-6
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-1.5B-Instruct}
  max_response_tokens: 4096
  max_model_len: 20480
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 20
  batch_size: 96
  explorer_input:
    taskset:
      name: countdown
      storage_type: file
      path: 'justinphan3110/Countdown-Tasks-3to4'
      split: 'train'
      format:
        prompt_key: 'nums'
        response_key: 'target'
      rollout_args:
        temperature: 1.0
        logprobs: 0
    eval_tasksets:
      - name: countdown-eval
        storage_type: file
        path: 'justinphan3110/Countdown-Tasks-3to4'
        split: 'test'
        format:
          prompt_key: 'nums'
          response_key: 'target'
        rollout_args:
          temperature: 0.4
    default_workflow_type: 'grpo_baseline_countdown_workflow'
  trainer_input:
    experience_buffer:
      name: countdown_grpo_baseline_1.5B_buffer
      storage_type: queue
      replay_buffer:
        enable: true
        priority_fn: decay_limit_randomization
      path: 'sqlite:///countdown_grpo_baseline_1.5B.db'
explorer:
  runner_per_model: 32
  eval_interval: 20
  rollout_model:
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: false
    dtype: bfloat16
    seed: 0
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
data_processor:
  experience_pipeline:
    operators:
      - name: "OPMD_filter"
synchronizer:
  sync_style: dynamic_by_explorer
  sync_method: 'nccl'
  sync_interval: 1
  sync_timeout: 12000
trainer:
  save_interval: 20
  grad_clip: 1.0
  use_dynamic_bsz: true
  max_token_len_per_gpu: 16384
  ulysses_sequence_parallel_size: 1
monitor:
  monitor_type: wandb
