project: "WEBSHOP"
name: "WEBSHOP_RFT_Qwen_1.5B_R3L"
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: opmd_reweight_adv
  repeat_times: 8
  optimizer:
    lr: 1e-6
model:
  model_path: ${oc.env:TRINITY_MODEL_PATH,Qwen/Qwen2.5-1.5B-Instruct}
  max_response_tokens: 4096
  max_model_len: 20480
cluster:
  node_num: 1
  gpu_per_node: 4
buffer:
  total_epochs: 20
  batch_size: 96
  explorer_input:
    taskset:
      name: webshop
      storage_type: file
      path: 'examples/R3L/webshop/webshop_data'
      split: 'train'
      format:
        prompt_key: 'task_id'
      rollout_args:
        temperature: 1.0
        logprobs: 0
    eval_tasksets:
      - name: webshop-eval
        storage_type: file
        path: 'examples/R3L/webshop/webshop_data'
        split: 'test'
        format:
          prompt_key: 'task_id'
        rollout_args:
          temperature: 1.0
    default_workflow_type: 'R3L_webshop_workflow'
  trainer_input:
    experience_buffer:
      name: webshop_R3L_1.5B_buffer
      storage_type: queue
      path: 'sqlite:///webshop_R3L_1.5B.db'
explorer:
  runner_per_model: 32
  eval_interval: 60
  rollout_model:
    engine_num: 2
    tensor_parallel_size: 1
    enable_prefix_caching: true
    enforce_eager: true
    dtype: bfloat16
    seed: 42
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
data_processor:
  experience_pipeline:
    operators:
      - name: "OPMD_filter"
synchronizer:
  sync_method: 'nccl'
  sync_interval: 1
  sync_timeout: 12000
trainer:
  save_interval: 200
  grad_clip: 1.0
  use_dynamic_bsz: true
  max_token_len_per_gpu: 16384
  ulysses_sequence_parallel_size: 1
